import 'package:get/get.dart';
class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'home.Enter_your_text': 'Enter your text',
'home.Password': 'Password',
'home.Save_Encrypted_Text': 'Save Encrypted Text',
'home.save_text_popup_desc_1': 'This text will only be saved locally on your device. You can access it later from the "Saved Texts" section on side drawer.',
'home.save_text_popup_desc_2': 'Your password will not be saved with the text.',
'home.Name_for_the_text': 'Name for the text',
'home.Please_enter_a_name_for_the_text': 'Please enter a name for the text',
'home.Save': 'Save',
'home.Menu': 'Menu',
'home.Saved_Texts': 'Saved Texts',
'home.Premium': 'Premium',
'home.Info': 'Info',
'home.Language': 'Language',
'home.Empty_Fields': 'Empty Fields',
'home.Please_enter_both_text_and_password_to_encrypt': 'Please enter both text and password to encrypt',
'home.Ok': 'Ok',
'home.Wrong_Password': 'Wrong Password',
'home.Password_you_entered_does_not_match': 'Password you entered does not match',
'home.Invalid_Input': 'Invalid Input',
'home.Invalid_text_or_password_entered': 'Invalid text or password entered',
'saved_texts.Saved_Encryptions': 'Saved Encryptions',
'saved_texts.No_saved_texts_found': 'No saved texts found.',
'saved_texts.desc_1': 'These encrypted texts are stored locally on your device.',
'saved_texts.desc_2': 'They will be deleted if you clear the app data. You can export or import them using the options menu in the top-right corner.',
'saved_texts.Confirm_Delete': 'Confirm Delete',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Are you sure you want to delete this text?',
'saved_texts.Cancel': 'Cancel',
'saved_texts.Delete': 'Delete',
'saved_texts.Decrypt': 'Decrypt',
'saved_texts.Share': 'Share',
'saved_texts.Export': 'Export',
'saved_texts.Import': 'Import',
'saved_texts.Success': 'Success',
'saved_texts.Text_saved_successfully': 'Text saved successfully!',
'saved_texts.Error': 'Error',
'saved_texts.Failed_to_save_text': 'Failed to save text.',
'saved_texts.Failed_to_load_saved_texts': 'Failed to load saved texts.',
'saved_texts.Text_deleted_successfully': 'Text deleted successfully!',
'saved_texts.Failed_to_delete_text': 'Failed to delete text.',
'saved_texts.Export_Successful': 'Export Successful',
'saved_texts.Saved_texts_exported_to': 'Saved texts exported to',
'saved_texts.Failed_to_export_saved_texts': 'Failed to export saved texts.',
'saved_texts.Failed_to_select_file': 'Failed to select file.',
'saved_texts.File_Not_Found': 'File Not Found',
'saved_texts.The_selected_file_does_not_exist': 'The selected file does not exist.',
'saved_texts.Failed_to_import_saved_texts': 'Failed to import saved texts.',
'saved_texts.Import_Successful': 'Import Successful',
'saved_texts.Saved_texts_imported_successfully': 'Saved texts imported successfully.',
'premium.Premium_Purchase': 'Premium Purchase',
'premium.desc_1': 'Support us and unlock a smoother, distraction free app. No more ads, just you and the content.',
'premium.desc_2': 'Upgrade once to enjoy lifetime Premium access with an ad-free experience forever.',
'premium.Premium': 'Premium',
'premium.Ad-free_experience': 'Ad-free experience.',
'premium.Lifetime_access': 'Lifetime access.',
'premium.Support_the_development_of_the_application': 'Support the development of the application.',
'premium.Active': 'Active',
'premium.Upgrade_to_Premium': 'Upgrade to Premium',
'premium.desc_3': 'Thank you for considering supporting our app! Your contribution helps us keep improving and providing a great experience.',
'premium.desc_4': 'If you have already purchased premium, please restore your purchase from the below button.',
'premium.Restore_Purchase': 'Restore Purchase',
'premium.Please_wait': 'Please wait...',
'premium.Remove_Ads': 'Remove Ads',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Remove ads and support the development of this app by purchasing premium for',
'premium.Cancel': 'Cancel',
'premium.Purchase': 'Purchase',
'premium.Purchase_successful': 'Purchase successful',
'premium.You_have_successfully_purchased_the_premium_membership': 'You have successfully purchased the premium membership.',
'premium.Transaction_failed': 'Transaction failed',
'premium.An_error_occurred_while_processing_your_purchase': 'An error occurred while processing your purchase:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'An error occurred while processing your purchase. Please try again later.',
'premium.Already_Subscribed': 'Already Subscribed',
'premium.You_already_have_an_active_subscription': 'You already have an active subscription.',
'premium.Subscription_Restored': 'Subscription Restored',
'premium.Your_subscription_has_been_restored_successfully': 'Your subscription has been restored successfully.',
'premium.No_Active_Subscription': 'No Active Subscription',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'No active subscription found. Please purchase a subscription.',
'info.Info': 'Info',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt is a simple and secure app for encrypting and decrypting text.',
'info.How_TextCrypt_Works': 'How TextCrypt Works',
'info.Step_1': 'Step 1: Get the Password',
'info.Step_1_desc': 'The user enters a password. This will be used to generate a secure key.',
'info.Step_2': 'Step 2: Add Salt',
'info.Step_2_desc': 'We combine the password with a \'salt\' (a random string) to make the result unique.',
'info.Step_3': 'Step 3: Strengthen the Password with PBKDF2',
'info.Step_3_desc': 'PBKDF2 uses SHA256 and 1000 rounds of hashing to make the password stronger and more secure.',
'info.Step_4': 'Step 4: Convert to Fixed-Length with MD5',
'info.Step_4_desc': 'The PBKDF2 result is hashed using MD5 to produce a 16-byte fixed-length key for AES.',
'info.Step_5': 'Step 5: Create AES Key',
'info.Step_5_desc': 'We convert the MD5 result into a key suitable for AES encryption.',
'info.Step_6': 'Step 6: Encrypt the Text',
'info.Step_6_desc': 'The user\'s text is encrypted using AES and the key created above.',
'info.Step_7': 'Final Output: Encrypted Text',
'info.Step_7_desc': 'The result looks like random characters and can only be decrypted using the correct password.',
'info.contact': 'If you have any questions or suggestions, feel free to reach out to us at: contact@eleetra.com',
'language.Select_your_preferred_language': 'Select your preferred language:',
'language.Change_Language': 'Change Language',
'language.Search_for_language': 'Search for language',
'language.note': 'Please note: These translations are machine-generated and haven\'t been manually reviewed. If you spot any issues, we sincerely apologize. Feel free to reach out at contact@eleetra.com. We’d love to hear your feedback and make things better!',
},
'it': {
'home.Enter_your_text': 'Inserisci il tuo testo',
'home.Password': 'Password',
'home.Save_Encrypted_Text': 'Salva il testo crittografato',
'home.save_text_popup_desc_1': 'Questo testo verrà salvato solo localmente sul tuo dispositivo. Potrai accedervi in ​​seguito dalla sezione "Testi salvati" nel cassetto laterale.',
'home.save_text_popup_desc_2': 'La password non verrà salvata insieme al testo.',
'home.Name_for_the_text': 'Nome per il testo',
'home.Please_enter_a_name_for_the_text': 'Inserisci un nome per il testo',
'home.Save': 'Salva',
'home.Menu': 'Menu',
'home.Saved_Texts': 'Testi salvati',
'home.Premium': 'Premio',
'home.Info': 'Informazioni',
'home.Language': 'Lingua',
'home.Empty_Fields': 'Campi vuoti',
'home.Please_enter_both_text_and_password_to_encrypt': 'Inserisci sia il testo che la password per crittografare',
'home.Ok': 'OK',
'home.Wrong_Password': 'Password errata',
'home.Password_you_entered_does_not_match': 'La password inserita non corrisponde',
'home.Invalid_Input': 'Input non valido',
'home.Invalid_text_or_password_entered': 'Testo o password non validi inseriti',
'saved_texts.Saved_Encryptions': 'Crittografie salvate',
'saved_texts.No_saved_texts_found': 'Nessun testo salvato trovato.',
'saved_texts.desc_1': 'Questi testi crittografati vengono memorizzati localmente sul tuo dispositivo.',
'saved_texts.desc_2': 'Verranno eliminati se cancelli i dati dell\'app. Puoi esportarli o importarli utilizzando il menu delle opzioni in alto a destra.',
'saved_texts.Confirm_Delete': 'Conferma Elimina',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Sei sicuro di voler eliminare questo testo?',
'saved_texts.Cancel': 'Cancellare',
'saved_texts.Delete': 'Eliminare',
'saved_texts.Decrypt': 'Decifrare',
'saved_texts.Share': 'Condividere',
'saved_texts.Export': 'Esportare',
'saved_texts.Import': 'Importare',
'saved_texts.Success': 'Successo',
'saved_texts.Text_saved_successfully': 'Testo salvato con successo!',
'saved_texts.Error': 'Errore',
'saved_texts.Failed_to_save_text': 'Impossibile salvare il testo.',
'saved_texts.Failed_to_load_saved_texts': 'Impossibile caricare i testi salvati.',
'saved_texts.Text_deleted_successfully': 'Testo eliminato con successo!',
'saved_texts.Failed_to_delete_text': 'Impossibile eliminare il testo.',
'saved_texts.Export_Successful': 'Esportazione riuscita',
'saved_texts.Saved_texts_exported_to': 'Testi salvati esportati in',
'saved_texts.Failed_to_export_saved_texts': 'Impossibile esportare i testi salvati.',
'saved_texts.Failed_to_select_file': 'Impossibile selezionare il file.',
'saved_texts.File_Not_Found': 'File non trovato',
'saved_texts.The_selected_file_does_not_exist': 'Il file selezionato non esiste.',
'saved_texts.Failed_to_import_saved_texts': 'Impossibile importare i testi salvati.',
'saved_texts.Import_Successful': 'Importazione riuscita',
'saved_texts.Saved_texts_imported_successfully': 'Testi salvati importati con successo.',
'premium.Premium_Purchase': 'Acquisto Premium',
'premium.desc_1': 'Sostieni la nostra iniziativa e scopri un\'app più fluida e senza distrazioni. Niente più pubblicità, solo tu e i contenuti.',
'premium.desc_2': 'Esegui l\'upgrade una volta per usufruire dell\'accesso Premium a vita con un\'esperienza senza pubblicità per sempre.',
'premium.Premium': 'Premio',
'premium.Ad-free_experience': 'Esperienza senza pubblicità.',
'premium.Lifetime_access': 'Accesso a vita.',
'premium.Support_the_development_of_the_application': 'Supportare lo sviluppo dell\'applicazione.',
'premium.Active': 'Attivo',
'premium.Upgrade_to_Premium': 'Passa a Premium',
'premium.desc_3': 'Grazie per aver scelto di supportare la nostra app! Il tuo contributo ci aiuta a continuare a migliorare e a offrire un\'esperienza fantastica.',
'premium.desc_4': 'Se hai già acquistato la versione premium, ripristina il tuo acquisto tramite il pulsante qui sotto.',
'premium.Restore_Purchase': 'Ripristina acquisto',
'premium.Please_wait': 'Attendere prego...',
'premium.Remove_Ads': 'Rimuovi annunci',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Rimuovi gli annunci e sostieni lo sviluppo di questa app acquistando la versione premium per',
'premium.Cancel': 'Cancellare',
'premium.Purchase': 'Acquistare',
'premium.Purchase_successful': 'Acquisto effettuato con successo',
'premium.You_have_successfully_purchased_the_premium_membership': 'Hai acquistato con successo l\'abbonamento premium.',
'premium.Transaction_failed': 'Transazione fallita',
'premium.An_error_occurred_while_processing_your_purchase': 'Si è verificato un errore durante l\'elaborazione dell\'acquisto:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Si è verificato un errore durante l\'elaborazione dell\'acquisto. Riprova più tardi.',
'premium.Already_Subscribed': 'Già iscritto',
'premium.You_already_have_an_active_subscription': 'Hai già un abbonamento attivo.',
'premium.Subscription_Restored': 'Abbonamento ripristinato',
'premium.Your_subscription_has_been_restored_successfully': 'Il tuo abbonamento è stato ripristinato con successo.',
'premium.No_Active_Subscription': 'Nessun abbonamento attivo',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Nessun abbonamento attivo trovato. Acquista un abbonamento.',
'info.Info': 'Informazioni',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt è un\'app semplice e sicura per crittografare e decrittografare testi.',
'info.How_TextCrypt_Works': 'Come funziona TextCrypt',
'info.Step_1': 'Passaggio 1: ottenere la password',
'info.Step_1_desc': 'L\'utente inserisce una password. Questa verrà utilizzata per generare una chiave sicura.',
'info.Step_2': 'Passaggio 2: aggiungere il sale',
'info.Step_2_desc': 'Combiniamo la password con un \'sale\' (una stringa casuale) per rendere il risultato univoco.',
'info.Step_3': 'Passaggio 3: rafforzare la password con PBKDF2',
'info.Step_3_desc': 'PBKDF2 utilizza SHA256 e 1000 cicli di hashing per rendere la password più forte e sicura.',
'info.Step_4': 'Passaggio 4: convertire in lunghezza fissa con MD5',
'info.Step_4_desc': 'Il risultato PBKDF2 viene sottoposto a hash utilizzando MD5 per produrre una chiave di lunghezza fissa di 16 byte per AES.',
'info.Step_5': 'Passaggio 5: creare la chiave AES',
'info.Step_5_desc': 'Convertiamo il risultato MD5 in una chiave adatta alla crittografia AES.',
'info.Step_6': 'Passaggio 6: crittografare il testo',
'info.Step_6_desc': 'Il testo dell\'utente viene crittografato utilizzando AES e la chiave creata sopra.',
'info.Step_7': 'Output finale: testo crittografato',
'info.Step_7_desc': 'Il risultato appare come caratteri casuali e può essere decifrato solo utilizzando la password corretta.',
'info.contact': 'Per qualsiasi domanda o suggerimento, non esitate a contattarci all\'indirizzo: contact@eleetra.com',
'language.Select_your_preferred_language': 'Seleziona la tua lingua preferita:',
'language.Change_Language': 'Cambia lingua',
'language.Search_for_language': 'Cerca per lingua',
'language.note': 'Nota: queste traduzioni sono generate automaticamente e non sono state riviste manualmente. Se riscontri problemi, ci scusiamo sinceramente. Non esitare a contattarci all\'indirizzo contact@eleetra.com. Ci piacerebbe ricevere il tuo feedback e migliorare il servizio!',
},
'fr': {
'home.Enter_your_text': 'Entrez votre texte',
'home.Password': 'Mot de passe',
'home.Save_Encrypted_Text': 'Enregistrer le texte crypté',
'home.save_text_popup_desc_1': 'Ce texte sera enregistré localement sur votre appareil. Vous pourrez y accéder ultérieurement depuis la section « Textes enregistrés » du panneau latéral.',
'home.save_text_popup_desc_2': 'Votre mot de passe ne sera pas enregistré avec le texte.',
'home.Name_for_the_text': 'Nom du texte',
'home.Please_enter_a_name_for_the_text': 'Veuillez saisir un nom pour le texte',
'home.Save': 'Sauvegarder',
'home.Menu': 'Menu',
'home.Saved_Texts': 'Textes enregistrés',
'home.Premium': 'Prime',
'home.Info': 'Informations',
'home.Language': 'Langue',
'home.Empty_Fields': 'Champs vides',
'home.Please_enter_both_text_and_password_to_encrypt': 'Veuillez saisir à la fois le texte et le mot de passe à crypter',
'home.Ok': 'D\'accord',
'home.Wrong_Password': 'Mot de passe incorrect',
'home.Password_you_entered_does_not_match': 'Le mot de passe que vous avez saisi ne correspond pas',
'home.Invalid_Input': 'Entrée invalide',
'home.Invalid_text_or_password_entered': 'Texte ou mot de passe invalide saisi',
'saved_texts.Saved_Encryptions': 'Chiffres enregistrés',
'saved_texts.No_saved_texts_found': 'Aucun texte enregistré trouvé.',
'saved_texts.desc_1': 'Ces textes cryptés sont stockés localement sur votre appareil.',
'saved_texts.desc_2': 'Ils seront supprimés si vous effacez les données de l\'application. Vous pouvez les exporter ou les importer via le menu d\'options en haut à droite.',
'saved_texts.Confirm_Delete': 'Confirmer la suppression',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Êtes-vous sûr de vouloir supprimer ce texte ?',
'saved_texts.Cancel': 'Annuler',
'saved_texts.Delete': 'Supprimer',
'saved_texts.Decrypt': 'Décrypter',
'saved_texts.Share': 'Partager',
'saved_texts.Export': 'Exporter',
'saved_texts.Import': 'Importer',
'saved_texts.Success': 'Succès',
'saved_texts.Text_saved_successfully': 'Texte enregistré avec succès !',
'saved_texts.Error': 'Erreur',
'saved_texts.Failed_to_save_text': 'Échec de l\'enregistrement du texte.',
'saved_texts.Failed_to_load_saved_texts': 'Échec du chargement des textes enregistrés.',
'saved_texts.Text_deleted_successfully': 'Texte supprimé avec succès !',
'saved_texts.Failed_to_delete_text': 'Échec de la suppression du texte.',
'saved_texts.Export_Successful': 'Exportation réussie',
'saved_texts.Saved_texts_exported_to': 'Textes enregistrés exportés vers',
'saved_texts.Failed_to_export_saved_texts': 'Échec de l\'exportation des textes enregistrés.',
'saved_texts.Failed_to_select_file': 'Échec de la sélection du fichier.',
'saved_texts.File_Not_Found': 'Fichier introuvable',
'saved_texts.The_selected_file_does_not_exist': 'Le fichier sélectionné n\'existe pas.',
'saved_texts.Failed_to_import_saved_texts': 'Échec de l\'importation des textes enregistrés.',
'saved_texts.Import_Successful': 'Importation réussie',
'saved_texts.Saved_texts_imported_successfully': 'Les textes enregistrés ont été importés avec succès.',
'premium.Premium_Purchase': 'Achat Premium',
'premium.desc_1': 'Soutenez-nous et découvrez une application plus fluide et sans distraction. Plus de publicités, juste vous et le contenu.',
'premium.desc_2': 'Effectuez une mise à niveau une fois pour profiter d\'un accès Premium à vie avec une expérience sans publicité pour toujours.',
'premium.Premium': 'Prime',
'premium.Ad-free_experience': 'Expérience sans publicité.',
'premium.Lifetime_access': 'Accès à vie.',
'premium.Support_the_development_of_the_application': 'Soutenir le développement de l\'application.',
'premium.Active': 'Actif',
'premium.Upgrade_to_Premium': 'Passez à Premium',
'premium.desc_3': 'Merci de soutenir notre application ! Votre contribution nous aide à nous améliorer et à vous offrir une expérience optimale.',
'premium.desc_4': 'Si vous avez déjà acheté Premium, veuillez restaurer votre achat à partir du bouton ci-dessous.',
'premium.Restore_Purchase': 'Restaurer l\'achat',
'premium.Please_wait': 'S\'il vous plaît, attendez...',
'premium.Remove_Ads': 'Supprimer les publicités',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Supprimez les publicités et soutenez le développement de cette application en achetant la version premium pour',
'premium.Cancel': 'Annuler',
'premium.Purchase': 'Achat',
'premium.Purchase_successful': 'Achat réussi',
'premium.You_have_successfully_purchased_the_premium_membership': 'Vous avez acheté avec succès l\'abonnement premium.',
'premium.Transaction_failed': 'La transaction a échoué',
'premium.An_error_occurred_while_processing_your_purchase': 'Une erreur s\'est produite lors du traitement de votre achat :',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Une erreur s\'est produite lors de votre achat. Veuillez réessayer ultérieurement.',
'premium.Already_Subscribed': 'Déjà abonné',
'premium.You_already_have_an_active_subscription': 'Vous avez déjà un abonnement actif.',
'premium.Subscription_Restored': 'Abonnement rétabli',
'premium.Your_subscription_has_been_restored_successfully': 'Votre abonnement a été restauré avec succès.',
'premium.No_Active_Subscription': 'Aucun abonnement actif',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Aucun abonnement actif trouvé. Veuillez souscrire un abonnement.',
'info.Info': 'Informations',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt est une application simple et sécurisée pour crypter et décrypter du texte.',
'info.How_TextCrypt_Works': 'Comment fonctionne TextCrypt',
'info.Step_1': 'Étape 1 : Obtenir le mot de passe',
'info.Step_1_desc': 'L\'utilisateur saisit un mot de passe. Celui-ci servira à générer une clé sécurisée.',
'info.Step_2': 'Étape 2 : Ajouter du sel',
'info.Step_2_desc': 'Nous combinons le mot de passe avec un « sel » (une chaîne aléatoire) pour rendre le résultat unique.',
'info.Step_3': 'Étape 3 : Renforcez le mot de passe avec PBKDF2',
'info.Step_3_desc': 'PBKDF2 utilise SHA256 et 1000 tours de hachage pour rendre le mot de passe plus fort et plus sécurisé.',
'info.Step_4': 'Étape 4 : Conversion en longueur fixe avec MD5',
'info.Step_4_desc': 'Le résultat PBKDF2 est haché à l\'aide de MD5 pour produire une clé de longueur fixe de 16 octets pour AES.',
'info.Step_5': 'Étape 5 : Créer une clé AES',
'info.Step_5_desc': 'Nous convertissons le résultat MD5 en une clé adaptée au cryptage AES.',
'info.Step_6': 'Étape 6 : Crypter le texte',
'info.Step_6_desc': 'Le texte de l\'utilisateur est crypté à l\'aide d\'AES et de la clé créée ci-dessus.',
'info.Step_7': 'Résultat final : texte crypté',
'info.Step_7_desc': 'Le résultat ressemble à des caractères aléatoires et ne peut être déchiffré qu\'à l\'aide du mot de passe correct.',
'info.contact': 'Si vous avez des questions ou des suggestions, n\'hésitez pas à nous contacter à : contact@eleetra.com',
'language.Select_your_preferred_language': 'Sélectionnez votre langue préférée:',
'language.Change_Language': 'Changer de langue',
'language.Search_for_language': 'Rechercher une langue',
'language.note': 'Remarque : ces traductions sont générées automatiquement et n\'ont pas été révisées manuellement. Si vous constatez des erreurs, veuillez nous en excuser. N\'hésitez pas à nous contacter à l\'adresse contact@eleetra.com. Nous aimerions connaître votre avis et améliorer notre site !',
},
'de': {
'home.Enter_your_text': 'Geben Sie Ihren Text ein',
'home.Password': 'Passwort',
'home.Save_Encrypted_Text': 'Verschlüsselten Text speichern',
'home.save_text_popup_desc_1': 'Dieser Text wird nur lokal auf Ihrem Gerät gespeichert. Sie können später im Bereich „Gespeicherte Texte“ in der Seitenleiste darauf zugreifen.',
'home.save_text_popup_desc_2': 'Ihr Passwort wird nicht mit dem Text gespeichert.',
'home.Name_for_the_text': 'Name für den Text',
'home.Please_enter_a_name_for_the_text': 'Bitte geben Sie einen Namen für den Text ein',
'home.Save': 'Speichern',
'home.Menu': 'Speisekarte',
'home.Saved_Texts': 'Gespeicherte Texte',
'home.Premium': 'Prämie',
'home.Info': 'Info',
'home.Language': 'Sprache',
'home.Empty_Fields': 'Leere Felder',
'home.Please_enter_both_text_and_password_to_encrypt': 'Bitte geben Sie sowohl Text als auch Passwort ein, um zu verschlüsseln',
'home.Ok': 'OK',
'home.Wrong_Password': 'Falsches Passwort',
'home.Password_you_entered_does_not_match': 'Das eingegebene Passwort stimmt nicht überein',
'home.Invalid_Input': 'Ungültige Eingabe',
'home.Invalid_text_or_password_entered': 'Ungültiger Text oder ungültiges Passwort eingegeben',
'saved_texts.Saved_Encryptions': 'Gespeicherte Verschlüsselungen',
'saved_texts.No_saved_texts_found': 'Keine gespeicherten Texte gefunden.',
'saved_texts.desc_1': 'Diese verschlüsselten Texte werden lokal auf Ihrem Gerät gespeichert.',
'saved_texts.desc_2': 'Sie werden gelöscht, wenn Sie die App-Daten löschen. Sie können sie über das Optionsmenü oben rechts exportieren oder importieren.',
'saved_texts.Confirm_Delete': 'Löschen bestätigen',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Möchten Sie diesen Text wirklich löschen?',
'saved_texts.Cancel': 'Stornieren',
'saved_texts.Delete': 'Löschen',
'saved_texts.Decrypt': 'Entschlüsseln',
'saved_texts.Share': 'Aktie',
'saved_texts.Export': 'Export',
'saved_texts.Import': 'Import',
'saved_texts.Success': 'Erfolg',
'saved_texts.Text_saved_successfully': 'Text erfolgreich gespeichert!',
'saved_texts.Error': 'Fehler',
'saved_texts.Failed_to_save_text': 'Text konnte nicht gespeichert werden.',
'saved_texts.Failed_to_load_saved_texts': 'Das Laden gespeicherter Texte ist fehlgeschlagen.',
'saved_texts.Text_deleted_successfully': 'Text erfolgreich gelöscht!',
'saved_texts.Failed_to_delete_text': 'Text konnte nicht gelöscht werden.',
'saved_texts.Export_Successful': 'Export erfolgreich',
'saved_texts.Saved_texts_exported_to': 'Gespeicherte Texte exportiert nach',
'saved_texts.Failed_to_export_saved_texts': 'Gespeicherte Texte konnten nicht exportiert werden.',
'saved_texts.Failed_to_select_file': 'Dateiauswahl fehlgeschlagen.',
'saved_texts.File_Not_Found': 'Datei nicht gefunden',
'saved_texts.The_selected_file_does_not_exist': 'Die ausgewählte Datei existiert nicht.',
'saved_texts.Failed_to_import_saved_texts': 'Gespeicherte Texte konnten nicht importiert werden.',
'saved_texts.Import_Successful': 'Import erfolgreich',
'saved_texts.Saved_texts_imported_successfully': 'Gespeicherte Texte erfolgreich importiert.',
'premium.Premium_Purchase': 'Premiumkauf',
'premium.desc_1': 'Unterstützen Sie uns und nutzen Sie eine flüssigere App ohne Ablenkungen. Keine Werbung mehr, nur Sie und der Inhalt.',
'premium.desc_2': 'Führen Sie ein einmaliges Upgrade durch, um lebenslangen Premium-Zugriff mit dauerhaft werbefreiem Erlebnis zu genießen.',
'premium.Premium': 'Prämie',
'premium.Ad-free_experience': 'Werbefreies Erlebnis.',
'premium.Lifetime_access': 'Lebenslanger Zugriff.',
'premium.Support_the_development_of_the_application': 'Unterstützen Sie die Entwicklung der Anwendung.',
'premium.Active': 'Aktiv',
'premium.Upgrade_to_Premium': 'Upgrade auf Premium',
'premium.desc_3': 'Vielen Dank, dass Sie unsere App unterstützen! Ihr Beitrag hilft uns, uns weiter zu verbessern und ein großartiges Erlebnis zu bieten.',
'premium.desc_4': 'Wenn Sie Premium bereits erworben haben, stellen Sie Ihren Kauf bitte über die Schaltfläche unten wieder her.',
'premium.Restore_Purchase': 'Kauf wiederherstellen',
'premium.Please_wait': 'Bitte warten...',
'premium.Remove_Ads': 'Anzeigen entfernen',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Entfernen Sie Anzeigen und unterstützen Sie die Entwicklung dieser App durch den Kauf von Premium für',
'premium.Cancel': 'Stornieren',
'premium.Purchase': 'Kaufen',
'premium.Purchase_successful': 'Kauf erfolgreich',
'premium.You_have_successfully_purchased_the_premium_membership': 'Sie haben die Premium-Mitgliedschaft erfolgreich erworben.',
'premium.Transaction_failed': 'Transaktion fehlgeschlagen',
'premium.An_error_occurred_while_processing_your_purchase': 'Bei der Bearbeitung Ihres Kaufs ist ein Fehler aufgetreten:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Bei der Kaufabwicklung ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.',
'premium.Already_Subscribed': 'Bereits abonniert',
'premium.You_already_have_an_active_subscription': 'Sie haben bereits ein aktives Abonnement.',
'premium.Subscription_Restored': 'Abonnement wiederhergestellt',
'premium.Your_subscription_has_been_restored_successfully': 'Ihr Abonnement wurde erfolgreich wiederhergestellt.',
'premium.No_Active_Subscription': 'Kein aktives Abonnement',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Kein aktives Abonnement gefunden. Bitte erwerben Sie ein Abonnement.',
'info.Info': 'Info',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt ist eine einfache und sichere App zum Verschlüsseln und Entschlüsseln von Text.',
'info.How_TextCrypt_Works': 'So funktioniert TextCrypt',
'info.Step_1': 'Schritt 1: Holen Sie sich das Passwort',
'info.Step_1_desc': 'Der Benutzer gibt ein Passwort ein. Dieses wird zur Generierung eines sicheren Schlüssels verwendet.',
'info.Step_2': 'Schritt 2: Salz hinzufügen',
'info.Step_2_desc': 'Wir kombinieren das Passwort mit einem „Salt“ (einer zufälligen Zeichenfolge), um das Ergebnis eindeutig zu machen.',
'info.Step_3': 'Schritt 3: Stärken Sie das Passwort mit PBKDF2',
'info.Step_3_desc': 'PBKDF2 verwendet SHA256 und 1000 Hashing-Runden, um das Passwort stärker und sicherer zu machen.',
'info.Step_4': 'Schritt 4: Konvertieren in feste Länge mit MD5',
'info.Step_4_desc': 'Das PBKDF2-Ergebnis wird mit MD5 gehasht, um einen 16 Byte langen Schlüssel mit fester Länge für AES zu erzeugen.',
'info.Step_5': 'Schritt 5: AES-Schlüssel erstellen',
'info.Step_5_desc': 'Wir wandeln das MD5-Ergebnis in einen für die AES-Verschlüsselung geeigneten Schlüssel um.',
'info.Step_6': 'Schritt 6: Verschlüsseln Sie den Text',
'info.Step_6_desc': 'Der Text des Benutzers wird mit AES und dem oben erstellten Schlüssel verschlüsselt.',
'info.Step_7': 'Endgültige Ausgabe: Verschlüsselter Text',
'info.Step_7_desc': 'Das Ergebnis sieht aus wie zufällige Zeichen und kann nur mit dem richtigen Passwort entschlüsselt werden.',
'info.contact': 'Wenn Sie Fragen oder Anregungen haben, können Sie uns gerne unter contact@eleetra.com erreichen.',
'language.Select_your_preferred_language': 'Wählen Sie Ihre bevorzugte Sprache:',
'language.Change_Language': 'Sprache ändern',
'language.Search_for_language': 'Suche nach Sprache',
'language.note': 'Bitte beachten Sie: Diese Übersetzungen sind maschinell erstellt und wurden nicht manuell überprüft. Sollten Sie Probleme feststellen, bitten wir um Entschuldigung. Kontaktieren Sie uns gerne unter contact@eleetra.com. Wir freuen uns über Ihr Feedback und helfen Ihnen gerne, die Dinge zu verbessern!',
},
'ru': {
'home.Enter_your_text': 'Введите текст',
'home.Password': 'Пароль',
'home.Save_Encrypted_Text': 'Сохранить зашифрованный текст',
'home.save_text_popup_desc_1': 'Этот текст будет сохранен только локально на вашем устройстве. Вы сможете получить к нему доступ позже из раздела «Сохраненные тексты» на боковой панели.',
'home.save_text_popup_desc_2': 'Ваш пароль не будет сохранен вместе с текстом.',
'home.Name_for_the_text': 'Название текста',
'home.Please_enter_a_name_for_the_text': 'Введите название текста.',
'home.Save': 'Сохранять',
'home.Menu': 'Меню',
'home.Saved_Texts': 'Сохраненные тексты',
'home.Premium': 'Премиум',
'home.Info': 'Информация',
'home.Language': 'Язык',
'home.Empty_Fields': 'Пустые поля',
'home.Please_enter_both_text_and_password_to_encrypt': 'Введите текст и пароль для шифрования.',
'home.Ok': 'Хорошо',
'home.Wrong_Password': 'Неправильный пароль',
'home.Password_you_entered_does_not_match': 'Введенный вами пароль не совпадает',
'home.Invalid_Input': 'Неверный ввод',
'home.Invalid_text_or_password_entered': 'Введен неверный текст или пароль',
'saved_texts.Saved_Encryptions': 'Сохраненные шифровки',
'saved_texts.No_saved_texts_found': 'Сохраненных текстов не найдено.',
'saved_texts.desc_1': 'Эти зашифрованные тексты хранятся локально на вашем устройстве.',
'saved_texts.desc_2': 'Они будут удалены, если вы очистите данные приложения. Вы можете экспортировать или импортировать их с помощью меню параметров в правом верхнем углу.',
'saved_texts.Confirm_Delete': 'Подтвердить удаление',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Вы уверены, что хотите удалить этот текст?',
'saved_texts.Cancel': 'Отмена',
'saved_texts.Delete': 'Удалить',
'saved_texts.Decrypt': 'Расшифровать',
'saved_texts.Share': 'Делиться',
'saved_texts.Export': 'Экспорт',
'saved_texts.Import': 'Импорт',
'saved_texts.Success': 'Успех',
'saved_texts.Text_saved_successfully': 'Текст успешно сохранен!',
'saved_texts.Error': 'Ошибка',
'saved_texts.Failed_to_save_text': 'Не удалось сохранить текст.',
'saved_texts.Failed_to_load_saved_texts': 'Не удалось загрузить сохраненные тексты.',
'saved_texts.Text_deleted_successfully': 'Текст успешно удален!',
'saved_texts.Failed_to_delete_text': 'Не удалось удалить текст.',
'saved_texts.Export_Successful': 'Экспорт успешен',
'saved_texts.Saved_texts_exported_to': 'Сохраненные тексты экспортированы в',
'saved_texts.Failed_to_export_saved_texts': 'Не удалось экспортировать сохраненные тексты.',
'saved_texts.Failed_to_select_file': 'Не удалось выбрать файл.',
'saved_texts.File_Not_Found': 'Файл не найден',
'saved_texts.The_selected_file_does_not_exist': 'Выбранный файл не существует.',
'saved_texts.Failed_to_import_saved_texts': 'Не удалось импортировать сохраненные тексты.',
'saved_texts.Import_Successful': 'Импорт успешен',
'saved_texts.Saved_texts_imported_successfully': 'Сохраненные тексты успешно импортированы.',
'premium.Premium_Purchase': 'Премиум покупка',
'premium.desc_1': 'Поддержите нас и разблокируйте более плавное, не отвлекающее приложение. Больше никакой рекламы, только вы и контент.',
'premium.desc_2': 'Оформите обновление один раз, чтобы пользоваться пожизненным Premium-доступом без рекламы.',
'premium.Premium': 'Премиум',
'premium.Ad-free_experience': 'Никакой рекламы.',
'premium.Lifetime_access': 'Пожизненный доступ.',
'premium.Support_the_development_of_the_application': 'Поддержите разработку приложения.',
'premium.Active': 'Активный',
'premium.Upgrade_to_Premium': 'Обновление до Премиум',
'premium.desc_3': 'Спасибо, что решили поддержать наше приложение! Ваш вклад помогает нам совершенствоваться и предоставлять отличный опыт.',
'premium.desc_4': 'Если вы уже приобрели премиум-подписку, восстановите покупку с помощью кнопки ниже.',
'premium.Restore_Purchase': 'Восстановить покупку',
'premium.Please_wait': 'Пожалуйста, подождите...',
'premium.Remove_Ads': 'Удалить рекламу',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Удалите рекламу и поддержите разработку этого приложения, купив премиум-подписку на',
'premium.Cancel': 'Отмена',
'premium.Purchase': 'Покупка',
'premium.Purchase_successful': 'Покупка прошла успешно',
'premium.You_have_successfully_purchased_the_premium_membership': 'Вы успешно приобрели премиум-членство.',
'premium.Transaction_failed': 'Транзакция не удалась',
'premium.An_error_occurred_while_processing_your_purchase': 'При обработке вашей покупки произошла ошибка:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Произошла ошибка при обработке вашей покупки. Повторите попытку позже.',
'premium.Already_Subscribed': 'Уже подписаны',
'premium.You_already_have_an_active_subscription': 'У вас уже есть активная подписка.',
'premium.Subscription_Restored': 'Подписка восстановлена',
'premium.Your_subscription_has_been_restored_successfully': 'Ваша подписка успешно восстановлена.',
'premium.No_Active_Subscription': 'Нет активной подписки',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Активная подписка не найдена. Пожалуйста, приобретите подписку.',
'info.Info': 'Информация',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt — простое и безопасное приложение для шифрования и дешифрования текста.',
'info.How_TextCrypt_Works': 'Как работает TextCrypt',
'info.Step_1': 'Шаг 1: Получите пароль',
'info.Step_1_desc': 'Пользователь вводит пароль. Он будет использован для генерации безопасного ключа.',
'info.Step_2': 'Шаг 2: Добавьте соль.',
'info.Step_2_desc': 'Мы объединяем пароль с «солью» (случайной строкой), чтобы сделать результат уникальным.',
'info.Step_3': 'Шаг 3: Усильте пароль с помощью PBKDF2',
'info.Step_3_desc': 'PBKDF2 использует SHA256 и 1000 раундов хеширования, чтобы сделать пароль более надежным и безопасным.',
'info.Step_4': 'Шаг 4: Преобразование в фиксированную длину с помощью MD5',
'info.Step_4_desc': 'Результат PBKDF2 хешируется с помощью MD5 для создания 16-байтового ключа фиксированной длины для AES.',
'info.Step_5': 'Шаг 5: Создайте ключ AES',
'info.Step_5_desc': 'Мы преобразуем результат MD5 в ключ, подходящий для шифрования AES.',
'info.Step_6': 'Шаг 6: Зашифруйте текст',
'info.Step_6_desc': 'Текст пользователя шифруется с помощью AES и созданного выше ключа.',
'info.Step_7': 'Конечный результат: зашифрованный текст',
'info.Step_7_desc': 'Результат выглядит как случайные символы и может быть расшифрован только с помощью правильного пароля.',
'info.contact': 'Если у вас есть вопросы или предложения, свяжитесь с нами по адресу: contact@eleetra.com',
'language.Select_your_preferred_language': 'Выберите предпочитаемый язык:',
'language.Change_Language': 'Изменить язык',
'language.Search_for_language': 'Поиск языка',
'language.note': 'Обратите внимание: эти переводы созданы машиной и не проверялись вручную. Если вы обнаружите какие-либо проблемы, мы искренне приносим извинения. Не стесняйтесь обращаться по адресу contact@eleetra.com. Мы будем рады услышать ваши отзывы и сделать все лучше!',
},
'zh': {
'home.Enter_your_text': '输入文本',
'home.Password': '密码',
'home.Save_Encrypted_Text': '保存加密文本',
'home.save_text_popup_desc_1': '此文本仅会保存在您的设备本地。您可以稍后从侧边栏的“已保存文本”部分访问它。',
'home.save_text_popup_desc_2': '您的密码不会与文本一起保存。',
'home.Name_for_the_text': '文本名称',
'home.Please_enter_a_name_for_the_text': '请输入文本名称',
'home.Save': '节省',
'home.Menu': '菜单',
'home.Saved_Texts': '已保存的文本',
'home.Premium': '优质的',
'home.Info': '信息',
'home.Language': '语言',
'home.Empty_Fields': '空旷的田野',
'home.Please_enter_both_text_and_password_to_encrypt': '请输入文本和密码进行加密',
'home.Ok': '好的',
'home.Wrong_Password': '密码错误',
'home.Password_you_entered_does_not_match': '您输入的密码不匹配',
'home.Invalid_Input': '无效输入',
'home.Invalid_text_or_password_entered': '输入的文本或密码无效',
'saved_texts.Saved_Encryptions': '已保存的加密',
'saved_texts.No_saved_texts_found': '未找到已保存的文本。',
'saved_texts.desc_1': '这些加密文本本地存储在您的设备上。',
'saved_texts.desc_2': '如果您清除应用数据，它们将被删除。您可以使用右上角的选项菜单导出或导入它们。',
'saved_texts.Confirm_Delete': '确认删除',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': '您确定要删除此文本吗？',
'saved_texts.Cancel': '取消',
'saved_texts.Delete': '删除',
'saved_texts.Decrypt': '解密',
'saved_texts.Share': '分享',
'saved_texts.Export': '出口',
'saved_texts.Import': '进口',
'saved_texts.Success': '成功',
'saved_texts.Text_saved_successfully': '文本保存成功！',
'saved_texts.Error': '错误',
'saved_texts.Failed_to_save_text': '保存文本失败。',
'saved_texts.Failed_to_load_saved_texts': '无法加载已保存的文本。',
'saved_texts.Text_deleted_successfully': '文本删除成功！',
'saved_texts.Failed_to_delete_text': '删除文本失败。',
'saved_texts.Export_Successful': '导出成功',
'saved_texts.Saved_texts_exported_to': '已保存的文本导出至',
'saved_texts.Failed_to_export_saved_texts': '无法导出已保存的文本。',
'saved_texts.Failed_to_select_file': '无法选择文件。',
'saved_texts.File_Not_Found': '未找到文件',
'saved_texts.The_selected_file_does_not_exist': '选定的文件不存在。',
'saved_texts.Failed_to_import_saved_texts': '无法导入已保存的文本。',
'saved_texts.Import_Successful': '导入成功',
'saved_texts.Saved_texts_imported_successfully': '已保存的文本已成功导入。',
'premium.Premium_Purchase': '高级购买',
'premium.desc_1': '支持我们，解锁更流畅、无干扰的应用。告别广告，只享受精彩内容。',
'premium.desc_2': '升级一次即可享受终身高级访问权限，并永远享受无广告的体验。',
'premium.Premium': '优质的',
'premium.Ad-free_experience': '无广告体验。',
'premium.Lifetime_access': '终身访问。',
'premium.Support_the_development_of_the_application': '支持应用程序的开发。',
'premium.Active': '积极的',
'premium.Upgrade_to_Premium': '升级至高级版',
'premium.desc_3': '感谢您考虑支持我们的应用！您的贡献有助于我们不断改进，提供更优质的体验。',
'premium.desc_4': '如果您已经购买了高级版，请通过下面的按钮恢复您的购买。',
'premium.Restore_Purchase': '恢复购买',
'premium.Please_wait': '请稍等...',
'premium.Remove_Ads': '移除广告',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': '删除广告并通过购买高级版来支持此应用程序的开发',
'premium.Cancel': '取消',
'premium.Purchase': '购买',
'premium.Purchase_successful': '购买成功',
'premium.You_have_successfully_purchased_the_premium_membership': '您已成功购买高级会员资格。',
'premium.Transaction_failed': '交易失败',
'premium.An_error_occurred_while_processing_your_purchase': '处理您的购买时发生错误：',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': '处理您的购买时出现错误。请稍后重试。',
'premium.Already_Subscribed': '已订阅',
'premium.You_already_have_an_active_subscription': '您已经有一个有效订阅。',
'premium.Subscription_Restored': '订阅已恢复',
'premium.Your_subscription_has_been_restored_successfully': '您的订阅已成功恢复。',
'premium.No_Active_Subscription': '没有有效订阅',
'premium.No_active_subscription_found_Please_purchase_a_subscription': '未找到有效订阅。请购买订阅。',
'info.Info': '信息',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt 是一款简单且安全的应用程序，用于加密和解密文本。',
'info.How_TextCrypt_Works': 'TextCrypt 的工作原理',
'info.Step_1': '步骤1：获取密码',
'info.Step_1_desc': '用户输入密码。这将用于生成安全密钥。',
'info.Step_2': '第二步：加盐',
'info.Step_2_desc': '我们将密码与“盐”（随机字符串）结合起来，使结果独一无二。',
'info.Step_3': '步骤3：使用PBKDF2增强密码',
'info.Step_3_desc': 'PBKDF2 使用 SHA256 和 1000 轮哈希算法来使密码更强大、更安全。',
'info.Step_4': '步骤 4：使用 MD5 转换为固定长度',
'info.Step_4_desc': 'PBKDF2 结果使用 MD5 进行散列，为 AES 生成 16 字节固定长度的密钥。',
'info.Step_5': '步骤5：创建AES密钥',
'info.Step_5_desc': '我们将MD5结果转换为适合AES加密的密钥。',
'info.Step_6': '步骤6：加密文本',
'info.Step_6_desc': '用户的文本使用 AES 和上面创建的密钥进行加密。',
'info.Step_7': '最终输出：加密文本',
'info.Step_7_desc': '结果看起来像随机字符，只有使用正确的密码才能解密。',
'info.contact': '如果您有任何问题或建议，请随时联系我们：contact@eleetra.com',
'language.Select_your_preferred_language': '选择您的首选语言：',
'language.Change_Language': '更改语言',
'language.Search_for_language': '搜索语言',
'language.note': '请注意：这些翻译由机器生成，未经人工审核。如果您发现任何问题，我们深表歉意。请随时通过 contact@eleetra.com 与我们联系。我们期待您的反馈，并不断改进！',
},
'es': {
'home.Enter_your_text': 'Introduce tu texto',
'home.Password': 'Contraseña',
'home.Save_Encrypted_Text': 'Guardar texto cifrado',
'home.save_text_popup_desc_1': 'Este texto solo se guardará localmente en tu dispositivo. Puedes acceder a él más tarde desde la sección "Textos guardados" del menú lateral.',
'home.save_text_popup_desc_2': 'Su contraseña no se guardará con el texto.',
'home.Name_for_the_text': 'Nombre para el texto',
'home.Please_enter_a_name_for_the_text': 'Por favor, introduzca un nombre para el texto',
'home.Save': 'Ahorrar',
'home.Menu': 'Menú',
'home.Saved_Texts': 'Textos guardados',
'home.Premium': 'De primera calidad',
'home.Info': 'Información',
'home.Language': 'Idioma',
'home.Empty_Fields': 'Campos vacíos',
'home.Please_enter_both_text_and_password_to_encrypt': 'Por favor, introduzca el texto y la contraseña para cifrar.',
'home.Ok': 'De acuerdo',
'home.Wrong_Password': 'Contraseña incorrecta',
'home.Password_you_entered_does_not_match': 'La contraseña ingresada no coincide',
'home.Invalid_Input': 'Entrada no válida',
'home.Invalid_text_or_password_entered': 'Texto o contraseña ingresados ​​no válidos',
'saved_texts.Saved_Encryptions': 'Cifrados guardados',
'saved_texts.No_saved_texts_found': 'No se encontraron textos guardados.',
'saved_texts.desc_1': 'Estos textos cifrados se almacenan localmente en su dispositivo.',
'saved_texts.desc_2': 'Se eliminarán si borras los datos de la aplicación. Puedes exportarlos o importarlos usando el menú de opciones en la esquina superior derecha.',
'saved_texts.Confirm_Delete': 'Confirmar eliminación',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': '¿Estás seguro que deseas eliminar este texto?',
'saved_texts.Cancel': 'Cancelar',
'saved_texts.Delete': 'Borrar',
'saved_texts.Decrypt': 'Descifrar',
'saved_texts.Share': 'Compartir',
'saved_texts.Export': 'Exportar',
'saved_texts.Import': 'Importar',
'saved_texts.Success': 'Éxito',
'saved_texts.Text_saved_successfully': '¡Texto guardado exitosamente!',
'saved_texts.Error': 'Error',
'saved_texts.Failed_to_save_text': 'No se pudo guardar el texto.',
'saved_texts.Failed_to_load_saved_texts': 'Error al cargar los textos guardados.',
'saved_texts.Text_deleted_successfully': '¡Texto eliminado exitosamente!',
'saved_texts.Failed_to_delete_text': 'No se pudo eliminar el texto.',
'saved_texts.Export_Successful': 'Exportación exitosa',
'saved_texts.Saved_texts_exported_to': 'Textos guardados exportados a',
'saved_texts.Failed_to_export_saved_texts': 'Error al exportar los textos guardados.',
'saved_texts.Failed_to_select_file': 'Error al seleccionar el archivo.',
'saved_texts.File_Not_Found': 'Archivo no encontrado',
'saved_texts.The_selected_file_does_not_exist': 'El archivo seleccionado no existe.',
'saved_texts.Failed_to_import_saved_texts': 'Error al importar los textos guardados.',
'saved_texts.Import_Successful': 'Importación exitosa',
'saved_texts.Saved_texts_imported_successfully': 'Textos guardados importados exitosamente.',
'premium.Premium_Purchase': 'Compra Premium',
'premium.desc_1': 'Apóyanos y consigue una app más fluida y sin distracciones. Sin anuncios, solo tú y el contenido.',
'premium.desc_2': 'Actualice una vez para disfrutar de acceso Premium de por vida con una experiencia sin publicidad para siempre.',
'premium.Premium': 'De primera calidad',
'premium.Ad-free_experience': 'Experiencia sin publicidad.',
'premium.Lifetime_access': 'Acceso de por vida.',
'premium.Support_the_development_of_the_application': 'Apoyar el desarrollo de la aplicación.',
'premium.Active': 'Activo',
'premium.Upgrade_to_Premium': 'Actualizar a Premium',
'premium.desc_3': '¡Gracias por apoyar nuestra app! Tu contribución nos ayuda a seguir mejorando y a ofrecerte una experiencia fantástica.',
'premium.desc_4': 'Si ya ha adquirido la versión premium, restaure su compra desde el botón que aparece a continuación.',
'premium.Restore_Purchase': 'Restaurar compra',
'premium.Please_wait': 'Espere por favor...',
'premium.Remove_Ads': 'Eliminar anuncios',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Elimina los anuncios y apoya el desarrollo de esta aplicación comprando la versión premium.',
'premium.Cancel': 'Cancelar',
'premium.Purchase': 'Compra',
'premium.Purchase_successful': 'Compra exitosa',
'premium.You_have_successfully_purchased_the_premium_membership': 'Has adquirido exitosamente la membresía premium.',
'premium.Transaction_failed': 'Transacción fallida',
'premium.An_error_occurred_while_processing_your_purchase': 'Se produjo un error al procesar su compra:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Se produjo un error al procesar tu compra. Inténtalo de nuevo más tarde.',
'premium.Already_Subscribed': 'Ya suscrito',
'premium.You_already_have_an_active_subscription': 'Ya tienes una suscripción activa.',
'premium.Subscription_Restored': 'Suscripción restaurada',
'premium.Your_subscription_has_been_restored_successfully': 'Su suscripción ha sido restaurada exitosamente',
'premium.No_Active_Subscription': 'Sin suscripción activa',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'No se encontró ninguna suscripción activa. Por favor, compre una suscripción.',
'info.Info': 'Información',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt es una aplicación sencilla y segura para cifrar y descifrar texto.',
'info.How_TextCrypt_Works': 'Cómo funciona TextCrypt',
'info.Step_1': 'Paso 1: Obtenga la contraseña',
'info.Step_1_desc': 'El usuario introduce una contraseña. Esta se utilizará para generar una clave segura.',
'info.Step_2': 'Paso 2: Agregar sal',
'info.Step_2_desc': 'Combinamos la contraseña con una \'sal\' (una cadena aleatoria) para que el resultado sea único.',
'info.Step_3': 'Paso 3: Fortalezca la contraseña con PBKDF2',
'info.Step_3_desc': 'PBKDF2 utiliza SHA256 y 1000 rondas de hash para hacer que la contraseña sea más fuerte y segura.',
'info.Step_4': 'Paso 4: Convertir a longitud fija con MD5',
'info.Step_4_desc': 'El resultado de PBKDF2 se codifica utilizando MD5 para producir una clave de longitud fija de 16 bytes para AES.',
'info.Step_5': 'Paso 5: Crear una clave AES',
'info.Step_5_desc': 'Convertimos el resultado MD5 en una clave adecuada para el cifrado AES.',
'info.Step_6': 'Paso 6: Cifrar el texto',
'info.Step_6_desc': 'El texto del usuario se cifra mediante AES y la clave creada anteriormente.',
'info.Step_7': 'Resultado final: texto cifrado',
'info.Step_7_desc': 'El resultado parece caracteres aleatorios y sólo se puede descifrar utilizando la contraseña correcta.',
'info.contact': 'Si tiene alguna pregunta o sugerencia, no dude en comunicarse con nosotros a: contact@eleetra.com',
'language.Select_your_preferred_language': 'Seleccione su idioma preferido:',
'language.Change_Language': 'Cambiar idioma',
'language.Search_for_language': 'Buscar idioma',
'language.note': 'Nota: Estas traducciones se generan automáticamente y no se han revisado manualmente. Si detecta algún error, le ofrecemos nuestras más sinceras disculpas. No dude en contactarnos en contact@eleetra.com. Nos encantaría conocer sus comentarios y mejorar la experiencia.',
},
'pt': {
'home.Enter_your_text': 'Digite seu texto',
'home.Password': 'Senha',
'home.Save_Encrypted_Text': 'Salvar texto criptografado',
'home.save_text_popup_desc_1': 'Este texto será salvo apenas localmente no seu dispositivo. Você poderá acessá-lo posteriormente na seção "Textos Salvos" na gaveta lateral.',
'home.save_text_popup_desc_2': 'Sua senha não será salva com o texto.',
'home.Name_for_the_text': 'Nome para o texto',
'home.Please_enter_a_name_for_the_text': 'Por favor, insira um nome para o texto',
'home.Save': 'Salvar',
'home.Menu': 'Menu',
'home.Saved_Texts': 'Textos salvos',
'home.Premium': 'Prêmio',
'home.Info': 'Informações',
'home.Language': 'Linguagem',
'home.Empty_Fields': 'Campos vazios',
'home.Please_enter_both_text_and_password_to_encrypt': 'Por favor, insira o texto e a senha para criptografar',
'home.Ok': 'OK',
'home.Wrong_Password': 'Senha errada',
'home.Password_you_entered_does_not_match': 'A senha digitada não corresponde',
'home.Invalid_Input': 'Entrada inválida',
'home.Invalid_text_or_password_entered': 'Texto ou senha inválidos inseridos',
'saved_texts.Saved_Encryptions': 'Criptografias salvas',
'saved_texts.No_saved_texts_found': 'Nenhum texto salvo encontrado.',
'saved_texts.desc_1': 'Esses textos criptografados são armazenados localmente no seu dispositivo.',
'saved_texts.desc_2': 'Eles serão excluídos se você limpar os dados do aplicativo. Você pode exportá-los ou importá-los usando o menu de opções no canto superior direito.',
'saved_texts.Confirm_Delete': 'Confirmar Excluir',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Tem certeza de que deseja excluir este texto?',
'saved_texts.Cancel': 'Cancelar',
'saved_texts.Delete': 'Excluir',
'saved_texts.Decrypt': 'Descriptografar',
'saved_texts.Share': 'Compartilhar',
'saved_texts.Export': 'Exportar',
'saved_texts.Import': 'Importar',
'saved_texts.Success': 'Sucesso',
'saved_texts.Text_saved_successfully': 'Texto salvo com sucesso!',
'saved_texts.Error': 'Erro',
'saved_texts.Failed_to_save_text': 'Falha ao salvar o texto.',
'saved_texts.Failed_to_load_saved_texts': 'Falha ao carregar textos salvos.',
'saved_texts.Text_deleted_successfully': 'Texto excluído com sucesso!',
'saved_texts.Failed_to_delete_text': 'Falha ao excluir o texto.',
'saved_texts.Export_Successful': 'Exportação bem-sucedida',
'saved_texts.Saved_texts_exported_to': 'Textos salvos exportados para',
'saved_texts.Failed_to_export_saved_texts': 'Falha ao exportar textos salvos.',
'saved_texts.Failed_to_select_file': 'Falha ao selecionar o arquivo.',
'saved_texts.File_Not_Found': 'Arquivo não encontrado',
'saved_texts.The_selected_file_does_not_exist': 'O arquivo selecionado não existe.',
'saved_texts.Failed_to_import_saved_texts': 'Falha ao importar textos salvos.',
'saved_texts.Import_Successful': 'Importação bem-sucedida',
'saved_texts.Saved_texts_imported_successfully': 'Textos salvos importados com sucesso.',
'premium.Premium_Purchase': 'Compra Premium',
'premium.desc_1': 'Apoie-nos e desbloqueie um aplicativo mais fluido e sem distrações. Chega de anúncios, só você e o conteúdo.',
'premium.desc_2': 'Atualize uma vez para aproveitar acesso Premium vitalício com uma experiência sem anúncios para sempre.',
'premium.Premium': 'Prêmio',
'premium.Ad-free_experience': 'Experiência sem anúncios.',
'premium.Lifetime_access': 'Acesso vitalício.',
'premium.Support_the_development_of_the_application': 'Apoiar o desenvolvimento do aplicativo.',
'premium.Active': 'Ativo',
'premium.Upgrade_to_Premium': 'Atualize para Premium',
'premium.desc_3': 'Agradecemos por apoiar nosso aplicativo! Sua contribuição nos ajuda a continuar melhorando e proporcionando uma ótima experiência.',
'premium.desc_4': 'Se você já comprou a versão premium, restaure sua compra no botão abaixo.',
'premium.Restore_Purchase': 'Restaurar Compra',
'premium.Please_wait': 'Por favor, aguarde...',
'premium.Remove_Ads': 'Remover anúncios',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Remova os anúncios e apoie o desenvolvimento deste aplicativo comprando o premium por',
'premium.Cancel': 'Cancelar',
'premium.Purchase': 'Comprar',
'premium.Purchase_successful': 'Compra realizada com sucesso',
'premium.You_have_successfully_purchased_the_premium_membership': 'Você adquiriu com sucesso a assinatura premium.',
'premium.Transaction_failed': 'A transação falhou',
'premium.An_error_occurred_while_processing_your_purchase': 'Ocorreu um erro ao processar sua compra:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Ocorreu um erro ao processar sua compra. Tente novamente mais tarde.',
'premium.Already_Subscribed': 'Já inscrito',
'premium.You_already_have_an_active_subscription': 'Você já tem uma assinatura ativa.',
'premium.Subscription_Restored': 'Assinatura restaurada',
'premium.Your_subscription_has_been_restored_successfully': 'Sua assinatura foi restaurada com sucesso.',
'premium.No_Active_Subscription': 'Nenhuma assinatura ativa',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Nenhuma assinatura ativa encontrada. Adquira uma assinatura.',
'info.Info': 'Informações',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt é um aplicativo simples e seguro para criptografar e descriptografar texto.',
'info.How_TextCrypt_Works': 'Como funciona o TextCrypt',
'info.Step_1': 'Etapa 1: Obtenha a senha',
'info.Step_1_desc': 'O usuário insere uma senha. Ela será usada para gerar uma chave segura.',
'info.Step_2': 'Passo 2: Adicione sal',
'info.Step_2_desc': 'Combinamos a senha com um \'salt\' (uma sequência aleatória) para tornar o resultado único.',
'info.Step_3': 'Etapa 3: Fortaleça a senha com PBKDF2',
'info.Step_3_desc': 'PBKDF2 usa SHA256 e 1000 rodadas de hash para tornar a senha mais forte e segura.',
'info.Step_4': 'Etapa 4: converter para comprimento fixo com MD5',
'info.Step_4_desc': 'O resultado do PBKDF2 é hash usando MD5 para produzir uma chave de comprimento fixo de 16 bytes para AES.',
'info.Step_5': 'Etapa 5: Criar chave AES',
'info.Step_5_desc': 'Convertemos o resultado MD5 em uma chave adequada para criptografia AES.',
'info.Step_6': 'Etapa 6: criptografar o texto',
'info.Step_6_desc': 'O texto do usuário é criptografado usando AES e a chave criada acima.',
'info.Step_7': 'Saída final: texto criptografado',
'info.Step_7_desc': 'O resultado parece caracteres aleatórios e só pode ser descriptografado usando a senha correta.',
'info.contact': 'Caso tenha alguma dúvida ou sugestão, entre em contato conosco pelo e-mail: contact@eleetra.com',
'language.Select_your_preferred_language': 'Selecione seu idioma preferido:',
'language.Change_Language': 'Alterar idioma',
'language.Search_for_language': 'Pesquisar por idioma',
'language.note': 'Observação: estas traduções são geradas automaticamente e não foram revisadas manualmente. Se você encontrar algum problema, pedimos sinceras desculpas. Sinta-se à vontade para entrar em contato pelo e-mail contact@eleetra.com. Adoraríamos receber seu feedback e melhorar as coisas!',
},
'uk': {
'home.Enter_your_text': 'Введіть свій текст',
'home.Password': 'Пароль',
'home.Save_Encrypted_Text': 'Зберегти зашифрований текст',
'home.save_text_popup_desc_1': 'Цей текст буде збережено лише локально на вашому пристрої. Ви можете отримати доступ до нього пізніше з розділу «Збережені тексти» на бічній панелі.',
'home.save_text_popup_desc_2': 'Ваш пароль не буде збережено разом із текстом.',
'home.Name_for_the_text': 'Назва до тексту',
'home.Please_enter_a_name_for_the_text': 'Будь ласка, введіть назву для тексту',
'home.Save': 'зберегти',
'home.Menu': 'Меню',
'home.Saved_Texts': 'Збережені тексти',
'home.Premium': 'Преміум',
'home.Info': 'Інформація',
'home.Language': 'Мова',
'home.Empty_Fields': 'Порожні поля',
'home.Please_enter_both_text_and_password_to_encrypt': 'Введіть текст і пароль для шифрування',
'home.Ok': 'добре',
'home.Wrong_Password': 'Неправильний пароль',
'home.Password_you_entered_does_not_match': 'Введений пароль не збігається',
'home.Invalid_Input': 'Недійсний вхід',
'home.Invalid_text_or_password_entered': 'Введено неправильний текст або пароль',
'saved_texts.Saved_Encryptions': 'Збережені шифрування',
'saved_texts.No_saved_texts_found': 'Збережених текстів не знайдено.',
'saved_texts.desc_1': 'Ці зашифровані тексти зберігаються локально на вашому пристрої.',
'saved_texts.desc_2': 'Їх буде видалено, якщо ви очистите дані програми. Ви можете експортувати або імпортувати їх за допомогою меню параметрів у верхньому правому куті.',
'saved_texts.Confirm_Delete': 'Підтвердьте видалення',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'Ви впевнені, що хочете видалити цей текст?',
'saved_texts.Cancel': 'Скасувати',
'saved_texts.Delete': 'Видалити',
'saved_texts.Decrypt': 'Розшифрувати',
'saved_texts.Share': 'Поділіться',
'saved_texts.Export': 'Експорт',
'saved_texts.Import': 'Імпорт',
'saved_texts.Success': 'Успіх',
'saved_texts.Text_saved_successfully': 'Текст успішно збережено!',
'saved_texts.Error': 'Помилка',
'saved_texts.Failed_to_save_text': 'Не вдалося зберегти текст.',
'saved_texts.Failed_to_load_saved_texts': 'Не вдалося завантажити збережені тексти.',
'saved_texts.Text_deleted_successfully': 'Текст успішно видалено!',
'saved_texts.Failed_to_delete_text': 'Не вдалося видалити текст.',
'saved_texts.Export_Successful': 'Експорт успішний',
'saved_texts.Saved_texts_exported_to': 'Збережені тексти експортовано в',
'saved_texts.Failed_to_export_saved_texts': 'Не вдалося експортувати збережені тексти.',
'saved_texts.Failed_to_select_file': 'Не вдалося вибрати файл.',
'saved_texts.File_Not_Found': 'Файл не знайдено',
'saved_texts.The_selected_file_does_not_exist': 'Вибраний файл не існує.',
'saved_texts.Failed_to_import_saved_texts': 'Не вдалося імпортувати збережені тексти.',
'saved_texts.Import_Successful': 'Імпорт успішний',
'saved_texts.Saved_texts_imported_successfully': 'Збережені тексти успішно імпортовано.',
'premium.Premium_Purchase': 'Преміальна покупка',
'premium.desc_1': 'Підтримайте нас і розблокуйте зручніший додаток, який не відволікатиметься. Більше жодної реклами, лише ви та вміст.',
'premium.desc_2': 'Оновіть один раз, щоб назавжди користуватися преміум-доступом без реклами.',
'premium.Premium': 'Преміум',
'premium.Ad-free_experience': 'Досвід без реклами.',
'premium.Lifetime_access': 'Довічний доступ.',
'premium.Support_the_development_of_the_application': 'Підтримка розробки програми.',
'premium.Active': 'Активний',
'premium.Upgrade_to_Premium': 'Оновіть до Premium',
'premium.desc_3': 'Дякуємо, що вирішили підтримати наш додаток! Ваш внесок допомагає нам продовжувати вдосконалюватися та забезпечувати чудовий досвід.',
'premium.desc_4': 'Якщо ви вже придбали преміум, відновіть покупку, натиснувши кнопку нижче.',
'premium.Restore_Purchase': 'Відновити покупку',
'premium.Please_wait': 'Будь ласка, зачекайте...',
'premium.Remove_Ads': 'Видалити рекламу',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'Видаліть рекламу та підтримайте розробку цієї програми, придбавши преміум для',
'premium.Cancel': 'Скасувати',
'premium.Purchase': 'Купівля',
'premium.Purchase_successful': 'Покупка успішна',
'premium.You_have_successfully_purchased_the_premium_membership': 'Ви успішно придбали преміум-членство.',
'premium.Transaction_failed': 'Помилка транзакції',
'premium.An_error_occurred_while_processing_your_purchase': 'Під час обробки вашої покупки сталася помилка:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'Під час обробки вашої покупки сталася помилка. Спробуйте пізніше.',
'premium.Already_Subscribed': 'Вже підписані',
'premium.You_already_have_an_active_subscription': 'У вас уже є активна підписка.',
'premium.Subscription_Restored': 'Підписку відновлено',
'premium.Your_subscription_has_been_restored_successfully': 'Вашу підписку успішно відновлено.',
'premium.No_Active_Subscription': 'Немає активної підписки',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'Активної підписки не знайдено. Будь ласка, придбайте підписку.',
'info.Info': 'Інформація',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'TextCrypt — це проста та безпечна програма для шифрування та дешифрування тексту.',
'info.How_TextCrypt_Works': 'Як працює TextCrypt',
'info.Step_1': 'Крок 1: Отримайте пароль',
'info.Step_1_desc': 'Користувач вводить пароль. Це буде використано для створення безпечного ключа.',
'info.Step_2': 'Крок 2: Додайте сіль',
'info.Step_2_desc': 'Ми поєднуємо пароль із «сіллю» (випадковим рядком), щоб зробити результат унікальним.',
'info.Step_3': 'Крок 3: посиліть пароль за допомогою PBKDF2',
'info.Step_3_desc': 'PBKDF2 використовує SHA256 і 1000 раундів хешування, щоб зробити пароль надійнішим і безпечнішим.',
'info.Step_4': 'Крок 4. Перетворення на фіксовану довжину за допомогою MD5',
'info.Step_4_desc': 'Результат PBKDF2 хешується за допомогою MD5 для отримання 16-байтового ключа фіксованої довжини для AES.',
'info.Step_5': 'Крок 5: Створіть ключ AES',
'info.Step_5_desc': 'Ми перетворюємо результат MD5 у ключ, придатний для шифрування AES.',
'info.Step_6': 'Крок 6: Зашифруйте текст',
'info.Step_6_desc': 'Текст користувача шифрується за допомогою AES і ключа, створеного вище.',
'info.Step_7': 'Кінцевий результат: зашифрований текст',
'info.Step_7_desc': 'Результат виглядає як випадкові символи, і його можна розшифрувати лише за допомогою правильного пароля.',
'info.contact': 'Якщо у вас є запитання чи пропозиції, не соромтеся зв’язатися з нами за адресою: contact@eleetra.com',
'language.Select_your_preferred_language': 'Виберіть бажану мову:',
'language.Change_Language': 'Змінити мову',
'language.Search_for_language': 'Пошук мови',
'language.note': 'Будь ласка, зверніть увагу: ці переклади створено машиною та не перевірялися вручну. Якщо ви помітили будь-які проблеми, ми щиро перепрошуємо. Не соромтеся звертатися за адресою contact@eleetra.com. Ми будемо раді почути ваші відгуки та покращити ситуацію!',
},
'hi': {
'home.Enter_your_text': 'अपना पाठ दर्ज करें',
'home.Password': 'पासवर्ड',
'home.Save_Encrypted_Text': 'एन्क्रिप्टेड टेक्स्ट सहेजें',
'home.save_text_popup_desc_1': 'यह टेक्स्ट केवल आपके डिवाइस पर स्थानीय रूप से सहेजा जाएगा। आप इसे बाद में साइड ड्रॉअर पर "सेव्ड टेक्स्ट" सेक्शन से एक्सेस कर सकते हैं।',
'home.save_text_popup_desc_2': 'आपका पासवर्ड पाठ के साथ सहेजा नहीं जाएगा.',
'home.Name_for_the_text': 'पाठ का नाम',
'home.Please_enter_a_name_for_the_text': 'कृपया पाठ के लिए एक नाम दर्ज करें',
'home.Save': 'बचाना',
'home.Menu': 'मेनू',
'home.Saved_Texts': 'सहेजे गए पाठ',
'home.Premium': 'अधिमूल्य',
'home.Info': 'जानकारी',
'home.Language': 'भाषा',
'home.Empty_Fields': 'खाली फ़ील्ड',
'home.Please_enter_both_text_and_password_to_encrypt': 'कृपया एन्क्रिप्ट करने के लिए टेक्स्ट और पासवर्ड दोनों दर्ज करें',
'home.Ok': 'ठीक है',
'home.Wrong_Password': 'ग़लत पासवर्ड',
'home.Password_you_entered_does_not_match': 'आपके द्वारा दर्ज किया गया पासवर्ड मेल नहीं खाता',
'home.Invalid_Input': 'अमान्य निवेश',
'home.Invalid_text_or_password_entered': 'गलत पाठ या पासवर्ड दर्ज किया गया',
'saved_texts.Saved_Encryptions': 'सहेजे गए एन्क्रिप्शन',
'saved_texts.No_saved_texts_found': 'कोई सहेजा गया पाठ नहीं मिला.',
'saved_texts.desc_1': 'ये एन्क्रिप्टेड टेक्स्ट आपके डिवाइस पर स्थानीय रूप से संग्रहीत होते हैं।',
'saved_texts.desc_2': 'यदि आप ऐप डेटा साफ़ करते हैं तो वे हटा दिए जाएँगे। आप उन्हें ऊपरी-दाएँ कोने में विकल्प मेनू का उपयोग करके निर्यात या आयात कर सकते हैं।',
'saved_texts.Confirm_Delete': 'मिटाने की पुष्टि करें',
'saved_texts.Are_you_sure_you_want_to_delete_this_text': 'क्या आप वाकई इस पाठ को हटाना चाहते हैं?',
'saved_texts.Cancel': 'रद्द करना',
'saved_texts.Delete': 'मिटाना',
'saved_texts.Decrypt': 'डिक्रिप्ट',
'saved_texts.Share': 'शेयर करना',
'saved_texts.Export': 'निर्यात',
'saved_texts.Import': 'आयात',
'saved_texts.Success': 'सफलता',
'saved_texts.Text_saved_successfully': 'पाठ सफलतापूर्वक सहेजा गया!',
'saved_texts.Error': 'गलती',
'saved_texts.Failed_to_save_text': 'पाठ सहेजने में विफल.',
'saved_texts.Failed_to_load_saved_texts': 'सहेजे गए पाठ लोड करने में विफल.',
'saved_texts.Text_deleted_successfully': 'पाठ सफलतापूर्वक हटा दिया गया!',
'saved_texts.Failed_to_delete_text': 'पाठ हटाने में विफल.',
'saved_texts.Export_Successful': 'निर्यात सफल',
'saved_texts.Saved_texts_exported_to': 'सहेजे गए पाठ निर्यात किए गए',
'saved_texts.Failed_to_export_saved_texts': 'सहेजे गए पाठ निर्यात करने में विफल.',
'saved_texts.Failed_to_select_file': 'फ़ाइल का चयन करने में विफल.',
'saved_texts.File_Not_Found': 'फ़ाइल प्राप्त नहीं हुई',
'saved_texts.The_selected_file_does_not_exist': 'चयनित फ़ाइल मौजूद नहीं है.',
'saved_texts.Failed_to_import_saved_texts': 'सहेजे गए पाठ आयात करने में विफल.',
'saved_texts.Import_Successful': 'आयात सफल',
'saved_texts.Saved_texts_imported_successfully': 'सहेजे गए पाठ सफलतापूर्वक आयातित.',
'premium.Premium_Purchase': 'प्रीमियम खरीद',
'premium.desc_1': 'हमारा समर्थन करें और एक सहज, विकर्षण मुक्त ऐप अनलॉक करें। अब कोई विज्ञापन नहीं, सिर्फ़ आप और सामग्री।',
'premium.desc_2': 'एक बार अपग्रेड करें और हमेशा के लिए विज्ञापन-मुक्त अनुभव के साथ आजीवन प्रीमियम एक्सेस का आनंद लें।',
'premium.Premium': 'अधिमूल्य',
'premium.Ad-free_experience': 'विज्ञापन-मुक्त अनुभव.',
'premium.Lifetime_access': 'आजीवन पहुंच.',
'premium.Support_the_development_of_the_application': 'अनुप्रयोग के विकास का समर्थन करें.',
'premium.Active': 'सक्रिय',
'premium.Upgrade_to_Premium': 'प्रीमियम में अपग्रेड करें',
'premium.desc_3': 'हमारे ऐप का समर्थन करने पर विचार करने के लिए धन्यवाद! आपका योगदान हमें बेहतर बनाने और एक बेहतरीन अनुभव प्रदान करने में मदद करता है।',
'premium.desc_4': 'यदि आपने पहले ही प्रीमियम खरीद लिया है, तो कृपया नीचे दिए गए बटन से अपनी खरीद को पुनर्स्थापित करें।',
'premium.Restore_Purchase': 'पुनःस्थापन क्रय',
'premium.Please_wait': 'कृपया प्रतीक्षा करें...',
'premium.Remove_Ads': 'विज्ञापन हटाएँ',
'premium.Remove_ads_and_support_the_development_of_this_app_by_purchasing_premium_for': 'विज्ञापन हटाएं और प्रीमियम खरीदकर इस ऐप के विकास का समर्थन करें',
'premium.Cancel': 'रद्द करना',
'premium.Purchase': 'खरीदना',
'premium.Purchase_successful': 'खरीदारी सफल हुई',
'premium.You_have_successfully_purchased_the_premium_membership': 'आपने सफलतापूर्वक प्रीमियम सदस्यता खरीद ली है।',
'premium.Transaction_failed': 'लेन - देन विफल',
'premium.An_error_occurred_while_processing_your_purchase': 'आपकी खरीदारी संसाधित करते समय एक त्रुटि हुई:',
'premium.An_error_occurred_while_processing_your_purchase._Please_try_again_later': 'आपकी खरीदारी संसाधित करते समय कोई त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।',
'premium.Already_Subscribed': 'पहले से सदस्यता ले रखी',
'premium.You_already_have_an_active_subscription': 'आपके पास पहले से ही एक सक्रिय सदस्यता है.',
'premium.Subscription_Restored': 'सदस्यता बहाल की गई',
'premium.Your_subscription_has_been_restored_successfully': 'आपकी सदस्यता सफलतापूर्वक बहाल कर दी गई है.',
'premium.No_Active_Subscription': 'कोई सक्रिय सदस्यता नहीं',
'premium.No_active_subscription_found_Please_purchase_a_subscription': 'कोई सक्रिय सदस्यता नहीं मिली। कृपया सदस्यता खरीदें।',
'info.Info': 'जानकारी',
'info.TextCrypt_is_a_simple_and_secure_app_for_encrypting_and_decrypting_text': 'टेक्स्टक्रिप्ट (TextCrypt) टेक्स्ट को एन्क्रिप्ट और डिक्रिप्ट करने के लिए एक सरल और सुरक्षित ऐप है।',
'info.How_TextCrypt_Works': 'टेक्स्टक्रिप्ट कैसे काम करता है',
'info.Step_1': 'चरण 1: पासवर्ड प्राप्त करें',
'info.Step_1_desc': 'उपयोगकर्ता एक पासवर्ड दर्ज करता है। इसका उपयोग सुरक्षित कुंजी बनाने के लिए किया जाएगा।',
'info.Step_2': 'चरण 2: नमक डालें',
'info.Step_2_desc': 'परिणाम को अद्वितीय बनाने के लिए हम पासवर्ड को \'सॉल्ट\' (एक यादृच्छिक स्ट्रिंग) के साथ जोड़ते हैं।',
'info.Step_3': 'चरण 3: PBKDF2 के साथ पासवर्ड को मजबूत करें',
'info.Step_3_desc': 'PBKDF2 पासवर्ड को अधिक मजबूत और सुरक्षित बनाने के लिए SHA256 और 1000 राउंड हैशिंग का उपयोग करता है।',
'info.Step_4': 'चरण 4: MD5 के साथ निश्चित-लंबाई में कनवर्ट करें',
'info.Step_4_desc': 'PBKDF2 परिणाम को MD5 का उपयोग करके हैश किया जाता है, जिससे AES के लिए 16-बाइट निश्चित-लंबाई वाली कुंजी तैयार होती है।',
'info.Step_5': 'चरण 5: AES कुंजी बनाएँ',
'info.Step_5_desc': 'हम MD5 परिणाम को AES एन्क्रिप्शन के लिए उपयुक्त कुंजी में परिवर्तित करते हैं।',
'info.Step_6': 'चरण 6: पाठ एन्क्रिप्ट करें',
'info.Step_6_desc': 'उपयोगकर्ता का पाठ AES और ऊपर बनाई गई कुंजी का उपयोग करके एन्क्रिप्ट किया जाता है।',
'info.Step_7': 'अंतिम आउटपुट: एन्क्रिप्टेड टेक्स्ट',
'info.Step_7_desc': 'परिणाम यादृच्छिक अक्षरों जैसा दिखता है और इसे केवल सही पासवर्ड का उपयोग करके ही डिक्रिप्ट किया जा सकता है।',
'info.contact': 'यदि आपके कोई प्रश्न या सुझाव हों, तो कृपया हमसे contact@eleetra.com पर संपर्क करें।',
'language.Select_your_preferred_language': 'अपनी पसंदीदा भाषा चुनें:',
'language.Change_Language': 'भाषा बदलें',
'language.Search_for_language': 'भाषा खोजें',
'language.note': 'कृपया ध्यान दें: ये अनुवाद मशीन द्वारा तैयार किए गए हैं और इनकी मैन्युअल समीक्षा नहीं की गई है। अगर आपको कोई समस्या नज़र आती है, तो हम ईमानदारी से माफ़ी चाहते हैं। बेझिझक contact@eleetra.com पर संपर्क करें। हमें आपकी प्रतिक्रिया सुनना और चीज़ों को बेहतर बनाना अच्छा लगेगा!',
},
        };
      }
      